version: '3.8'

services:
  ai-agent:
    build: .
    container_name: ai-agent
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - cash-net

networks:
  cash-net:
    external: true
    name: cash-ecomm_cash-net
